### ISSUE TITLE
[API Platform] input always a string, array / etc expected

### ISSUE THREAD

**Issue by dkarlovi** [rollersearch/search#175]
| Q                     | A
| --------------------- | -----
| Bug report?           | yes
| Feature request?      | no
| BC Break report?      | no
| RFC?                  | no

This might be me doing something wrong, but I think API Platform integration shouldn't work as it stands now:

1. [it takes a `search` param from request](https://github.com/rollerworks/search-api-platform/blob/master/src/Processor/ApiSearchProcessor.php#L63)
2. [it passes it to `processInput()` as is](https://github.com/rollerworks/search-api-platform/blob/master/src/Processor/ApiSearchProcessor.php#L64)
3. [`processInput` checks it's an non-empty array](https://github.com/rollerworks/search-api-platform/blob/master/src/Processor/ApiSearchProcessor.php#L78-L80), but this can never be true as it's taken verbatim from request, without doing any normalization so, at that point, it **must** be a string

So, whatever I do, it will always result in an empty query. Debugging this is what made me create #174 because it was really unclear what's going wrong.

**Comment by sstok** [comment]
Are you calling the processor in a test (this requires the parameter is provided as an array unless you use the Request string processing) or with an actual request?

**Comment by dkarlovi** [comment]
Actual request, inside an app.

**Comment by sstok** [comment]
OK, is it possible you can provide a small minimum Symfony application to reproduce this issue?

**Comment by dkarlovi** [comment]
I guess so, yes. In the meantime, shouldn't it work exactly like described from the code, does it not work like that for you, as I see nothing that would convert a query string to an array?

**Comment by sstok** [comment]
I remembered I have a working copy of the API platform 😅 (the _complete_ documentation is missing for this integration).

The query parameter expects an array that is processable by `ArrayInput`, you can use the [ArrayExporter](https://github.com/rollerworks/search/blob/master/src/Exporter/ArrayExporter.php) to export a SearchCondition to the correct format (the exporter uses the Norm formatter of the FieldType).

See also http://rollerworkssearch.readthedocs.io/en/latest/composing_search_conditions.html for composing a SearchCondition.

**Comment by dkarlovi** [comment]
> you can use the ArrayExporter to export a SearchCondition to the correct format

Use where? If I'm using API Platform, the integration will invoke the search processor, I'm not doing anything to the input. Should I register an event handler here to transform the search query or something?

**Comment by dkarlovi** [comment]
So, I'm doing: http://127.0.0.1:8000/api/images?search=fields[name][simple-values][0]=abc

Breaking [here](https://github.com/rollerworks/search-api-platform/blob/master/src/Processor/ApiSearchProcessor.php#L78), I get:

`$input="fields[name][simple-values][0]=abc"`

in the debugger. I've only installed the integration, enabled for a test entity and added a fieldset:

```xml
<!-- Resources/config/api_resources/resources.xml -->
        <attribute name="rollerworks_search">
            <attribute name="contexts">
                <attribute name="_defaults">
                    <attribute name="fieldset">ImageBundle\Search\FieldSet\ImageFieldSet</attribute>
                </attribute>
                <attribute name="_any">
                    <attribute name="doctrine_orm">
                        <attribute name="mappings">
                            <attribute name="id">id</attribute>
                            <attribute name="name">name</attribute>
                        </attribute>
                    </attribute>
                </attribute>
            </attribute>
        </attribute>
```

```php
<?php
# Search/FieldSet/ImageFieldSet.php ￼

declare(strict_types=1);

namespace ImageBundle\Search\FieldSet;

use Rollerworks\Component\Search\Extension\Core\Type;
use Rollerworks\Component\Search\FieldSetBuilder;
use Rollerworks\Component\Search\FieldSetConfigurator;

/**
 * Class ImageFieldSet.
 */
class ImageFieldSet implements FieldSetConfigurator
{
    /**
     * Configure the FieldSet builder.
     *
     * @param FieldSetBuilder $builder
     */
    public function buildFieldSet(FieldSetBuilder $builder): void
    {
        $builder
            ->add('id', Type\TextType::class)
            ->add('name', Type\TextType::class);
    }
}
```

**Comment by dkarlovi** [comment]
So, I've swapped out [this](https://github.com/rollerworks/search-api-platform/blob/master/src/Processor/ApiSearchProcessor.php#L63) with:

```php
        $str = $request->query->get('search');
        $input = [];
        if (null !== $str) {
            parse_str($str, $input);
        }
```

and it works now, query string is properly converted to an associative array. Don't know if this is supposed to happen automatically somehow, I know PHP does this for POST, can't remember about GET.

**Comment by sstok** [comment]
Don't worry ;) I made the exact same mistake when testing 😅

**Comment by dkarlovi** [comment]
That only goes to show `ArrayInput` via GET is probably too complex to use without a builder SDK, needs more #176. :)
